In [11]:
import numpy as np

In [9]:
#initilializing an array
arr=np.array([1,2,3,4,5,6])
print(arr)

a = np.array([1+2j, 3+4j, 5+6j])
print(a)
print(type(a))

[1 2 3 4 5 6]
[1.+2.j 3.+4.j 5.+6.j]
<class 'numpy.ndarray'>


In [12]:
#Dimension and Size
a=np.array([[1,4,3,3,3,3,3],[1,2,2,2,2,3,3]])
print(a)
print(a.ndim)
a.size


[[1 4 3 3 3 3 3]
 [1 2 2 2 2 3 3]]
2


14

In [12]:
#Addition
X = np.array([[12,7,3],
    [4 ,5,6],
    [7 ,8,9]])
Y = np.array([[5,8,1],
    [6,7,3],
    [4,5,9]])


print(X+Y)

[[17 15  4]
 [10 12  9]
 [11 13 18]]


In [17]:
#Transpose
X.transpose()

array([[12,  4,  7],
       [ 7,  5,  8],
       [ 3,  6,  9]])

In [18]:
#Dot Product
np.dot(X,Y)


array([[114, 160,  60],
       [ 74,  97,  73],
       [119, 157, 112]])

In [19]:
#Hadamard Multiplication
np.multiply(X,Y)

array([[60, 56,  3],
       [24, 35, 18],
       [28, 40, 81]])

In [13]:
#Accessing rows and columns
X = np.array([[12,7,3],
    [4 ,5,6],
    [7 ,8,9]])
print(X[1,1])
print(X[1])
print(X[:,[2]])

5
[4 5 6]
[[3]
 [6]
 [9]]


In [43]:
#slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[:4])
print(arr[-3:-1])
print(arr[-3:])
print(arr[1:5:2])

[2 3 4 5]
[1 2 3 4]
[5 6]
[5 6 7]
[2 4]


In [47]:
#reversing a list
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[len(arr)-1::-1])

[7 6 5 4 3 2 1]


In [14]:
X = np.array([[12,7,3],
    [4 ,5,6],
    [7 ,8,9]])
print(X[1,1:])

[5 6]


In [8]:
import csv
with open('winequality-red.csv','r') as file:
    wines=list(csv.reader(file, delimiter=';'))
print(wines[:3])

[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality'], ['7.4', '0.7', '0', '1.9', '0.076', '11', '34', '0.9978', '3.51', '0.56', '9.4', '5'], ['7.8', '0.88', '0', '2.6', '0.098', '25', '67', '0.9968', '3.2', '0.68', '9.8', '5']]
